# version: '3'

# services:
#   app:
#     image: 'sba'
#     build: .
#     ports:
#       - '4000:4000'


version: '3.2'
services:
  server:
    image: node:12-alpine
    working_dir: /server
    command: ./node_modules/nodemon/bin/nodemon.js app.js 4000
    volumes:
      - type: bind
        source: ./server
        target: /server
    ports:
      - "4000:4000"